[project]
name = "fixitydb-prototype"
version = "1.0.0-dev"
dependencies = [
    "click",
    "jwcrypto",
    "plastron-models",
    "plastron-repo",
    "python-dotenv",
    "rdflib",
    "requests",
    "requests-jwtauth",
]

[project.scripts]
check = "postgrest.cli:check"
load_uris = "postgrest.cli:load_uris"
